### ISSUE TITLE
Layout der Stellenanzeige soll angepasst werden

### ISSUE THREAD

**Issue by cbleek** [cbleek/Aviation#1]
Das Layout einer Anzeige soll an das Corporate Design angepasst werden.

Beispiel:

https://www.jobtool24-system.com/emails_auftrag/templates_html/anzeigentemplate_407820_1604.html?jobsite=Res_Extern&jobsiteID=1&tt=70629%20Stuttgart%20_Flugbegleiter%20(m/w/d)

@wkorolew die Anzeige hat ein dern Header und den Footer zusammen in einem Hintergrundbild. Kannst Du mir das Bild zerschneiden, damit man es getrennt im HTML einsetzen kann?

**Comment by wkorolew** [comment]
Done!

![1-DC-Aviation-Header](https://user-images.githubusercontent.com/55985319/76417435-26c9dc00-639d-11ea-9c54-e7c48ea51ebd.png)
![2-DC-Aviation-Footer](https://user-images.githubusercontent.com/55985319/76417436-27fb0900-639d-11ea-813f-5939f5658817.png)

**Comment by cbleek** [comment]
Danke. Dann bau doch bitte die Bilder in das Template einer Anzeige

Das Template findest du hier

https://github.com/cbleek/Aviation/tree/master/view/jobs/templates

**Comment by cbleek** [comment]
@HORDCA Layout wurde angepasst. Details machen wir in #3

Beispiel:

https://aviation.yawik.org/de/jobs/view?id=5e677fe2731b3b10d0144582
