### ISSUE TITLE
Workflow 

### ISSUE THREAD

**Issue by cbleek** [cbleek/Aviation#10]
Eingehende Bewerbungen sollen erst an die Fachabteilung gehen.

**Comment by TiSiE** [comment]
Hierbei sind noch folgende Punkte aufgefallen:

* [x] Wenn der Abteilungsleiter auf den Link in der Bestätigungsmail klickt und er noch nicht angemeldet ist, wird ein Server Error angezeigt. Hier sollte die Login-Maske erscheinen. (siehe https://github.com/cross-solution/YAWIK/issues/566)
* [ ] Default-Texte für die E-Mails fehlen noch

**Comment by TiSiE** [comment]
Da die Lösung für Punkt 1 in Yawik doch sehr umständlich geriet, ist die Funktionalität jetzt durch einen Bootstrap-Listener im Aviation-Modul umgesetzt.
