### ISSUE TITLE
Workflow Bewerbung

### ISSUE THREAD

**Issue by cbleek** [cbleek/Aviation#20]
In diesem Issue wollen wir den Workflow einer Bewerbung optimieren

**Comment by TiSiE** [comment]
Es gibt momentan einen Workflow für Bewerbungen:

1. Bewerbung wird vom Bewerber abgeschickt.
2. Abteilungsleiter wird benachrichtigt. Er kann Bewerbungen freigeben oder ablehnen.
3. zuständiger Sachbearbeiter wird benachrichtigt und kann die Bewerbung weiter bearbeiten.

Der Workflow soll aber eher folgendermaßen aussehen:

1. Bewerbung trifft ein, Personalsachbearbeiter werden benachrichtigt.
2. Sachbearbeiter leiten aussichtsreiche Bewerbungen an den Abteilungsleiter.

Was danach passieren soll, hat mir @cbleek noch nicht dargelegt. denkbar wäre folgendes

3.
   1. Abteilungsleiter gibt Bewerbungen "frei" oder lehnt sie ab, Sachbearbeiter organisieren Vorstellungsgespräche, etc.
   2. Abteilungsleiter organisiert selbst Vorstellungsgespräche, etc.

-----

Auf jeden Fall bedarf es Anpassungen am Yawik.
* Neues Settings-Formular für den Workflow für die Organization
* Handling des Workflows im Applications-Modul.
* UI-Anpassungen
