### ISSUE TITLE
Entfernung Zusammenfassung bei Eingabe Stellenanzeige

### ISSUE THREAD

**Issue by cbleek** [cbleek/Aviation#4]
Am Ende der Eingabe einer Anzeige soll die Zusammenfassung entfernt werden.

@HORDCA richtig?

![Auswahl_547](https://user-images.githubusercontent.com/858642/76517495-afa84c80-645d-11ea-997e-8b044da18f41.png)

**Comment by cbleek** [comment]
auf der letzten Seite sehe ich die Zusammenfassung noch

![Bildschirmfoto 2020-04-25 um 20 17 04](https://user-images.githubusercontent.com/858642/80287667-e0ed8b00-8732-11ea-962a-0ebdd20ff217.png)

**Comment by TiSiE** [comment]
Ich habe vergessen, den FPM-Service neuzustarten.

Funktioniert jetzt wie gesollt :)
