### ISSUE TITLE
Entfernung Multiposting und Notiz an Kunden

### ISSUE THREAD

**Issue by cbleek** [cbleek/Aviation#5]
Bei der Eingabe einer Anzeige sollen die Felder "Multiposting" und "Notiz des Kunden" entfernt werden.

@HORDCA richtig?

![Auswahl_548](https://user-images.githubusercontent.com/858642/76517749-2cd3c180-645e-11ea-83ed-e1d97632f7b9.png)

**Comment by TiSiE** [comment]
Für Fieldsets gibt es ein Interface, das implementiert werden muss:  
[CustomizableFieldsetInterface](https://github.com/cross-solution/YAWIK/blob/master/module/Core/src/Form/CustomizableFieldsetInterface.php)

dann können mithilfe einer Instanz von [FieldsetCustomizationOptions](https://github.com/cross-solution/YAWIK/blob/master/module/Core/src/Options/FieldsetCustomizationOptions.php) (und einer config-Datei) die einzelnen Felder oder Unter-Fieldsets modifiziert werden (auch deaktiviert).

Multiposting und Kundennotiz sind aber dedizierte Formulare im Job-Container. Um diese zu entfernen, gibt es mind. 2 Möglichkeiten:

1. Eine delegator-Factory für den Job-Container schreiben, die die entspr. Formulare deaktiviert.
2. Einen Listener für den Eventmanager 'Jobs/JobContainer/Evetns' schreiben, der auf das INIT event hört.

die erste Möglichkeit ist die eleganteste.

**Comment by cbleek** [comment]
Deployed wurde. Aber das Multiposting Feld wird noch angezeigt.

Muss da noch eine Konfiguration hochgeladen werden?

**Comment by TiSiE** [comment]
In meiner Entwicklungsumgebung funktioniert es.

**Comment by TiSiE** [comment]
Online wird die Konfiguration nicht ausgelesen.

**Comment by TiSiE** [comment]
Der PHP Fast-fm service cached Dateisystem-Zugriffe.
Er muss nach einem Deploy neugestartet werden. (Die von YAWIK gecachte config unter `var/cache/module-config-cache.php` natürlich auch)
