### ISSUE TITLE
Auswahl des Ortes als Select-Box

### ISSUE THREAD

**Issue by TiSiE** [cbleek/Aviation#8]
Bei nur wenigen möglichen Orten (Dienstsitzen) ist es vermutlich einfacher, statt einer generellen Eingabe des Ortes mit Auto-Vervollständigung, eine Select-Box mit den entsprechenden Orten zu verwenden:

![select-location](https://user-images.githubusercontent.com/2029304/76527546-b63fbf80-646f-11ea-9881-fae98987f216.png)

@HORDCA  fyi

**Comment by cbleek** [comment]
Ich hatte dazu mal was in unsere Docs geschrieben. Aber wie genau die Konfiguration aussehen muss fehlt.
 
https://yawik.readthedocs.io/en/latest/faq/faq-geo-simple-location.html#is-it-possible-to-use-a-certain-list-of-locations
